# Generated by Django 5.0.6 on 2024-07-06 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0004_delete_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name', 'date_added'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
